/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Conversation
         * @description Markdown transcript with ``Content-Disposition: attachment``. Generated only here.
         */
        get: operations["export_conversation_api_conversations__conversation_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Store the user message and start a run (one agent turn for direct chats; one bounded
         *     two-round exchange for group discussions). 409 ``run_active`` if a run is in progress.
         */
        post: operations["send_message_api_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Providers
         * @description Provider/model catalog from OpenCode. ``refresh=true`` re-queries OpenCode.
         */
        get: operations["get_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Events */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Cancel a running run. Idempotent: returns the run's current state.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Agent */
        Agent: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Persona */
            persona: string;
            /** Provider Id */
            provider_id: string;
            /** Revision */
            revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentCreate */
        AgentCreate: {
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Persona */
            persona: string;
            /** Provider Id */
            provider_id: string;
        };
        /**
         * AgentSnapshot
         * @description Immutable copy of an agent's configuration at the moment a run started.
         */
        AgentSnapshot: {
            /** Agent Id */
            agent_id: string;
            /** Model Id */
            model_id: string;
            /** Name */
            name: string;
            /** Persona */
            persona: string;
            /** Provider Id */
            provider_id: string;
            /** Revision */
            revision: number;
        };
        /**
         * AgentUpdate
         * @description PATCH body. Omitted fields are unchanged. ``archived`` archives/unarchives.
         */
        AgentUpdate: {
            /** Archived */
            archived?: boolean | null;
            /** Model Id */
            model_id?: string | null;
            /** Name */
            name?: string | null;
            /** Persona */
            persona?: string | null;
            /** Provider Id */
            provider_id?: string | null;
        };
        /** Conversation */
        Conversation: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Participant Ids */
            participant_ids: string[];
            /** Title */
            title: string;
            /** Topic */
            topic?: string | null;
            type: components["schemas"]["ConversationType"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Participant Ids */
            participant_ids: string[];
            /** Title */
            title?: string | null;
            /** Topic */
            topic?: string | null;
            type: components["schemas"]["ConversationType"];
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Active Run Id */
            active_run_id?: string | null;
            conversation: components["schemas"]["Conversation"];
            /** Messages */
            messages: components["schemas"]["Message"][];
        };
        /**
         * ConversationType
         * @enum {string}
         */
        ConversationType: "direct" | "group";
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "not_found" | "validation_error" | "provider_unavailable" | "model_unavailable" | "rate_limited" | "budget_exhausted" | "run_active" | "runtime_error";
        /** ErrorResponse */
        ErrorResponse: {
            /** Agent Id */
            agent_id?: string | null;
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Opencode Healthy */
            opencode_healthy: boolean;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** Message */
        Message: {
            /** @default null */
            agent: components["schemas"]["AgentSnapshot"] | null;
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** @default null */
            error_code: components["schemas"]["ErrorCode"] | null;
            /** Id */
            id: string;
            /**
             * Model Id
             * @default null
             */
            model_id: string | null;
            /**
             * Provider Id
             * @default null
             */
            provider_id: string | null;
            /**
             * Reply To Id
             * @default null
             */
            reply_to_id: string | null;
            role: components["schemas"]["MessageRole"];
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /** Speaker Name */
            speaker_name: string;
            /**
             * Stage
             * @default null
             */
            stage: number | null;
            status: components["schemas"]["MessageStatus"];
        };
        /** MessageCompletedEvent */
        MessageCompletedEvent: {
            message: components["schemas"]["Message"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.completed";
        };
        /** MessageDeltaEvent */
        MessageDeltaEvent: {
            /** Delta */
            delta: string;
            /** Message Id */
            message_id: string;
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.delta";
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "agent";
        /** MessageStartedEvent */
        MessageStartedEvent: {
            message: components["schemas"]["Message"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message.started";
        };
        /**
         * MessageStatus
         * @enum {string}
         */
        MessageStatus: "streaming" | "complete" | "cancelled" | "failed";
        /** ModelInfo */
        ModelInfo: {
            /** Context Limit */
            context_limit?: number | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            price?: components["schemas"]["ModelPrice"] | null;
        };
        /**
         * ModelPrice
         * @description USD per one million tokens, when OpenCode supplies it.
         */
        ModelPrice: {
            /** Input Per Mtok */
            input_per_mtok?: number | null;
            /** Output Per Mtok */
            output_per_mtok?: number | null;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Connected */
            connected: boolean;
            /** Id */
            id: string;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
            /** Name */
            name: string;
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
            /**
             * Refreshed At
             * Format: date-time
             */
            refreshed_at: string;
        };
        /** Run */
        Run: {
            /** Conversation Id */
            conversation_id: string;
            /** @default null */
            coordinator: components["schemas"]["AgentSnapshot"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** @default null */
            error_code: components["schemas"]["ErrorCode"] | null;
            /**
             * Finished At
             * @default null
             */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Participants */
            participants: components["schemas"]["AgentSnapshot"][];
            status: components["schemas"]["RunStatus"];
            usage?: components["schemas"]["Usage"];
        };
        /** RunCancelledEvent */
        RunCancelledEvent: {
            run: components["schemas"]["Run"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.cancelled";
        };
        /** RunCompletedEvent */
        RunCompletedEvent: {
            run: components["schemas"]["Run"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.completed";
        };
        RunEvent: components["schemas"]["RunStartedEvent"] | components["schemas"]["MessageStartedEvent"] | components["schemas"]["MessageDeltaEvent"] | components["schemas"]["MessageCompletedEvent"] | components["schemas"]["RunCompletedEvent"] | components["schemas"]["RunFailedEvent"] | components["schemas"]["RunCancelledEvent"] | components["schemas"]["RunPausedEvent"];
        /** RunFailedEvent */
        RunFailedEvent: {
            run: components["schemas"]["Run"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.failed";
        };
        /** RunPausedEvent */
        RunPausedEvent: {
            /** Reason */
            reason: string;
            run: components["schemas"]["Run"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.paused";
        };
        /** RunStartedEvent */
        RunStartedEvent: {
            run: components["schemas"]["Run"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.started";
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "completed" | "cancelled" | "failed" | "paused";
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            /** Run Id */
            run_id: string;
            /** User Message Id */
            user_message_id: string;
        };
        /** Settings */
        Settings: {
            /** Coordinator Agent Id */
            coordinator_agent_id?: string | null;
            /**
             * Coordinator Max Tokens
             * @default 2048
             */
            coordinator_max_tokens: number;
            /**
             * Openrouter Monthly Budget Usd
             * @default 5
             */
            openrouter_monthly_budget_usd: number;
            /**
             * Openrouter Spent Usd
             * @default 0
             */
            openrouter_spent_usd: number;
            /**
             * Participant Max Tokens
             * @default 1024
             */
            participant_max_tokens: number;
            /**
             * Project Brief
             * @default
             */
            project_brief: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Coordinator Agent Id */
            coordinator_agent_id?: string | null;
            /** Coordinator Max Tokens */
            coordinator_max_tokens?: number | null;
            /** Openrouter Monthly Budget Usd */
            openrouter_monthly_budget_usd?: number | null;
            /** Participant Max Tokens */
            participant_max_tokens?: number | null;
            /** Project Brief */
            project_brief?: string | null;
        };
        /** Usage */
        Usage: {
            /**
             * Cost Usd
             * @default null
             */
            cost_usd: number | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_agents_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_agent_api_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_conversation_api_conversations__conversation_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "text/plain": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message_api_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_providers_api_providers_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream; each `data:` is a RunEvent JSON object (see components). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
